# Generated by Django 5.2.17 on 2026-09-17 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('secondary', 'Secondary school'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's degree"), ('master', "Master's degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_current', '-created_at', 'id'],
            },
        ),
    ]
